[package]
name = "quest4"
version = "0.1.0"
authors = ["tariq"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quest3 ={path = "/home/tariq/assgnno7/quest3"}

